# Generated by Django 3.2.13 on 2022-06-01 12:50

import core.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the product', max_length=20)),
                ('description', models.TextField(blank=True, help_text='description of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product', max_digits=6)),
                ('label', models.CharField(choices=[('NEW', 'NEW'), ('REFURBISHED', 'REFURBISHED')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=30)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='the categeory this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='category.category')),
                ('ratings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.productrating')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['created'],
            },
            bases=(models.Model, core.models.EnablePartialUpdateMixin),
        ),
    ]
