# Generated by Django 4.0.4 on 2022-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='the title of the product', max_length=100),
        ),
    ]
